import React from 'react'

export const metadata = {
  title: "Contact | Techno",
  description: "Generated by create next app",
};


const ContactPage = () => {
  return (
    <div>ContactPage</div>
  )
}

export default ContactPage